language: python
cache:
  - apt
  - directories:
    - $HOME/.pip-cache/
    - $HOME/virtualenv/python2.7
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
# command to install python dependencies and program
install:
  - env
  - make pip
  - make install
# command to run tests
script:
  - nosetests --cover-package=raspy,raspyweb,raspyui --with-coverage
# package dependencies
before_install:
  - env
  - sudo apt-get update -y -qq
  - sudo make apt
