language: python
cache:
  - apt
  - directories:
    - $HOME/.pip-cache/
    - $HOME/virtualenv/python2.7
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
# command to install dependencies
install:
  - pip install setuptools --download-cache $HOME/.pip-cache
  - pip install docutils --download-cache $HOME/.pip-cache
  - make install
# command to run tests
script: nosetests
# package dependencies
before_install:
 - sudo apt-get update -y -qq
 - sudo apt-get install -y -qq build-essential python-dev python-minimal python python2.7-dev python2.7-minimal python2.7 git pylint
 - sudo apt-get install -y -qq libcairo2-dev libpango1.0-dev libglib2.0-dev libxml2-dev librrd-dev
 - sudo apt-get remove -y -qq python-zmq libzmq1 libzmq-dev
